### ISSUE TITLE
Can't link the library

### ISSUE THREAD

**Issue by maoesx** [adobe/react-native-acpcore#42]
### Expected Behaviour
After install the acpcore with npm, run "react-native link react-native-acpcore" should link the library to the app.

### Actual Behaviour
showing error message 
"Error: Failed to get dependency config
    at getDependencyConfig (appPath/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (appPath/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
    at Promise.resolve.then (appPath/node_modules/@react-native-community/cli/build/cliEntry.js:152:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"

#### Steps to Reproduce
1.Have an existing react native app
2.cd MyReactApp
3.npm install @adobe/react-native-acpcore --save
4.react-native link react-native-acpcore

#### Platform and Version
Node v10.15.0
Npm 6.4.1
react-native-cli: 2.0.1
react-native: 0.59.3

**Comment by nporter-adbe** [comment]
HI @maoesx, can you share the the full log output when you run `"react-native link react-native-acpcore`? I'm able to link in new projects without issue.

**Comment by nporter-adbe** [comment]
@maoesx it should be `react-native link @adobe/react-native-acpcore`. Do we have some incorrect docs somewhere?

**Comment by maoesx** [comment]
Yes, there's an error in the readme: 
2.1 Link
React Native 0.60+
CLI autolink feature links the module while building the app.

React Native <= 0.59
$ **react-native link react-native-acpcore** (should be react-native link @adobe/react-native-acpcore)

Anyway, the new command works for me, thanks!

**Comment by nporter-adbe** [comment]
@maoesx Thanks for pointing out the typo, I'll get that corrected. Glad the suggestion worked on your end.
